# Generated by Django 2.0.4 on 2019-01-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_auto_20190126_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
