# Generated by Django 2.1.5 on 2019-01-28 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guide', '0006_auto_20190126_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('type_of_service', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to='service_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
