# Generated by Django 2.1.5 on 2019-01-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_userservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservices',
            name='name_of_service',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
