# Generated by Django 2.1.5 on 2019-01-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_auto_20190129_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservices',
            name='name_of_service',
            field=models.CharField(max_length=50),
        ),
    ]
