# Generated by Django 2.1.5 on 2019-01-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_auto_20190129_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='userservices',
            name='short_description',
            field=models.CharField(default='Not Available', help_text='Short description of your service(2 to 3 sentences)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userservices',
            name='special_features',
            field=models.TextField(blank=True, help_text='Mention unique/special features if any'),
        ),
        migrations.AddField(
            model_name='userservices',
            name='total_cost',
            field=models.IntegerField(default=0, help_text='In nRs'),
            preserve_default=False,
        ),
    ]
