# Generated by Django 2.1.5 on 2019-01-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_auto_20190130_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservices',
            name='total_cost',
        ),
    ]
