# Generated by Django 2.1.5 on 2019-01-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0016_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
            preserve_default=False,
        ),
    ]
